name: Test Frontend
on:
  push:
    branches: [develop,main]
  workflow_dispatch:
jobs:
  build-n-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        continue-on-error: false
        run: cd frontend && npm install
      - name: Run test
        run: cd frontend &&  npm run test
      
