name: Test Frontend
on:
  push:
    branches: [develop,main]
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        continue-on-error: false
        run: cd frontend && npm install
      - name: Run test
        run: cd frontend &&  npm run test
      - name: Connect to cloudflare server as a User 
        run : |
          apt-get install sshpass
          touch ~/.ssh/config
          echo -e "Host ssh.shrawankp.com.np\nProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" > ~/.ssh/config
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
      - name: Test SSH
        run: sshpass -p ${{secrets.KRATOS_SSH_PASSWORD}} ssh root@${{secrets.KRATOS_SSH_HOST}}
        # run: ssh -i ~/.ssh/key.pem root@shrawankp.com.np
